showLandMarks = True  # Display landmarks
soundDetected = True  # Turn on sound or off
letter_confidence_time = 1.5  # Time threshold for letter confidence
voice_version = 1  # Version of voice model
show_face_detection = False  # To isplay face detection
show_body_detection = False  # To display body detection
camera_id = 0  # ID of camera device
cap_width = 1280  # Width of video frame
cap_height = 720  # Height of video frame
min_detection_confidence = 0.7  # Minimum confidence for detection
min_tracking_confidence = 0.5  # Minimum confidence for tracking
show_terminal_output = False  # To display terminal output global values
background_color_option = "grey"  # Text background color
background_color = (50, 50, 50)  # RGB values for background color
hand_detected_color_bg = (139, 0, 0)  # RGB values for hand detected background color
hand_detected_color_option = "default"  # Hand detected background color